version: '3'
services:
    flask:
        container_name: flask
        image: flask
        environment: 
            - POSTGRES_DB=developer
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=devpassword
            - POSTGRES_URL=127.0.0.1:25000
        ports:
            - "5000:5000"
        networks:
            - backend
        depends_on:
                - redis
                - postgres
        links:
            - redis
            - postgres
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - "80:80"
        networks:
            - backend
        depends_on: 
            - flask
    postgres:
        image: postgres:10
        environment:
            - POSTGRES_DB=developer
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=devpassword
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "25000:5432"
        expose:
            - "25000"
    redis:
        image: redis:latest
        ports:
            - "25100:6379"
        command: redis-server --save ""        
networks:
    backend:
        driver: bridge
volumes:
    postgres-data:
        driver: local