version: '3'
services:
    flask:
        container_name: flask
        build: ./flask
        environment: 
            - POSTGRES_DB=developer
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=devpassword
            - POSTGRES_URL=postgres
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - "5000:5000"
        networks:
            - web_network
            - db_network
        depends_on:
            - redis
            - postgres
        links:
            - redis
            - postgres
        restart: always
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "80:80"
        networks:
            - web_network
        depends_on:
            - flask
        restart: always
    postgres:
        container_name: postgres
        image: postgres:10
        environment:
            - POSTGRES_DB=developer
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=devpassword
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "25000:5432"
        expose:
            - "5432"
        networks:
            - db_network
        restart: always
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "25100:6379"
        command: redis-server --save ""
        networks:
            - db_network
        restart: always
networks:
    web_network:
        driver: bridge
    db_network:
        driver: bridge
volumes:
    postgres-data:
        driver: local